package backend.moviestore.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Movie {

    @Id  // unique ID
    @GeneratedValue(strategy = GenerationType.AUTO) // automatically generated by database
    private long id;
    private String title;
    private int releaseYear;
    private double price;

    // getterit ja setterit
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public int getReleaseYear() {
        return releaseYear;
    }
    public void setReleaseYear(int releaseYear) {
        this.releaseYear = releaseYear;
    }
    public double getPrice() {
        return price;
    }
    public void setPrice(double price) {
        this.price = price;
    }

    // constructors
    public Movie() {}

    public Movie(String title, int releaseYear, double price) {
        this.title = title;
        this.releaseYear = releaseYear;
        this.price = price;
    }

    // toString
    @Override
    public String toString() {
        return "Movie [id=" + id + ", title=" + title + ", releaseYear=" + releaseYear + ", price=" + price + "]";
    }

    

    
    
}
